apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - name: path-to-context
      description: The path to the build context
      default: /start/storm-tracker
    - name: path-to-deployment-file
      description: The path to the deployment file 
      default: deployment.yaml
    - name: path-to-dockerfile
      description: The path to the dockerfile to build
      default: Dockerfile
    - name: api-url
      description: ibmcloud api url
      default: cloud.ibm.com
    - name: container-repo-url
      description: Base url for container repository
      default: us.icr.io
    - name: container-repo-namespace
      description: Namespace where image image is located
      default: living-on-the-cloud
    - name: deployment-image
      description: Name of image to be deployed
      default: storm-tracker
    - name: name-of-cluster
      description: The number of cluster to deploy the image to
    - name: cluster-region
      description: The region where the cluster resides
      default: us-south
    - name: mvn-goals
      description: The Maven goals to run
      type: array
      default: ["package"]
    - name: git-access-token
      description: API Token for accessing private git repo
    - name: git-repo-url
      description: URL to git project that is being built 
    - name: commit-id
      description: Commit id to be pulled
  workspaces:
    - name: git-repo 
      description: Workspace for holding the cloned source code from the git-repo
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone-repo
    params:
      - name: git-access-token
        value: $(params.git-access-token)
      - name: repository
        value: $(params.git-repo-url)
      - name: revision
        value: $(params.commit-id)
    workspaces:
      - name: output
        workspace: git-repo
  - name: maven-build-java-artifact-from-source
    taskRef:
      name: maven-build-java-artifact-from-source
    runAfter:
      - git-clone
    params:
      - name: mvn-goals
        type: array
        value: ["package"]
      - name: path-to-context
        value: /start/storm-tracker
    workspaces:
      - name: source
        workspace: git-repo
  - name: build-image-send-to-cr
    taskRef:
      name: build-image-and-push-image
    runAfter:
      - maven-build-java-artifact-from-source
    params:
    - name: container-repo-url
      value: us.icr.io
    - name: container-repo-namespace
      value: living-on-the-cloud
    - name: deployment-image
      value: storm-tracker
    - name: path-to-context
      value: /start/storm-tracker
    workspaces:
      - name: source
        workspace: git-repo
  - name: deploy-image-to-ibm-cloud
    taskRef:
      name: deploy-image-to-ibm-cloud
    runAfter:
      - build-image-send-to-cr
    params:
    - name: path-to-context
      value: /start/storm-tracker
    - name: path-to-deployment-file
      value: deployment.yaml
    - name: name-of-cluster
      value: mycluster
    - name: container-repo-url
      value: us.icr.io
    - name: container-repo-namespace
      value: living-on-the-cloud
    - name: deployment-image
      value: storm-tracker
    - name: cluster-region
      value: us-south
    workspaces:
      - name: source
        workspace: git-repo