apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: storm-tracker
  name: storm-tracker
spec:
  selector:
    matchLabels:
      run: storm-tracker
  template:
    metadata:
      labels:
        run: storm-tracker
    spec:
      containers:
      - image: IMAGE
        imagePullPolicy: Always
        name: storm-tracker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: storm-tracker
  name: storm-tracker-port
spec:
  type: NodePort
  selector:
    run: storm-tracker
  ports:
    - port: 8080
      name: http